#!/bin/sh

OSMAND_APPNAME="OsmAnd~"
OSMAND_VERSION="2.0.2"
OSMAND_VERCODE="202"
OSMAND_SUBDIR="android/OsmAnd"

# '+' enables, '-' disables
# As found in upstream's jenkins log
# OSMAND_FEATURES="-play_market -gps_status -parking_plugin -blackberry +amazon -route_nav"
# Our slightly modified version
OSMAND_FEATURES="-play_market +gps_status -parking_plugin -blackberry -amazon -route_nav"

err() {
	echo ERROR: "$@"
	exit 1
}

if [ -d $OSMAND_SUBDIR ]
then
	cd $OSMAND_SUBDIR || err "Could not enter $OSMAND_SUBBDIR subdirectory"
fi

# Build native code
./old-ndk-build.sh || err "Failed to build native code"

export TARGET_APP_NAME="$OSMAND_APPNAME"
export APP_NAME="$OSMAND_APPNAME"
export APP_FEATURES="$OSMAND_FEATURES"
export APK_NUMBER_VERSION="$OSMAND_VERCODE"

sed -e '/qt.*Compile/d' -i build.gradle
sed -e '/signingConfig\s\+signingConfigs\./d' -i build.gradle
