#!/bin/sh

OSMAND_APPNAME="OsmAnd~"
OSMAND_VERSION="2.0.1"
OSMAND_VERCODE="201"
OSMAND_SUBDIR="android/OsmAnd"

# '+' enables, '-' disables
# As found in upstream's jenkins log
# OSMAND_FEATURES="-play_market -gps_status -parking_plugin -blackberry +amazon -route_nav"
# Our slightly modified version
OSMAND_FEATURES="-play_market +gps_status -parking_plugin -blackberry -amazon -route_nav"

err() {
	echo ERROR: "$@"
	exit 1
}

# They use ANDROID_SDK instead of ANDROID_HOME
if [ -z $ANDROID_SDK ] && [ -n $ANDROID_HOME ]
then
	export ANDROID_SDK="$ANDROID_HOME"
fi

if [ -d $OSMAND_SUBDIR ]
then
	cd $OSMAND_SUBDIR || err "Could not enter $OSMAND_SUBBDIR subdirectory"
fi

# Replace the name given to the full paid app
sed -i "s/\"OsmAnd+\"/\"$OSMAND_APPNAME\"/g" build.xml || err "Could not replace application name"

# Build native code
./old-ndk-build.sh || err "Failed to build native code"

export TARGET_APP_NAME="$OSMAND_APPNAME"
export APP_NAME="$OSMAND_APPNAME"
export APP_FEATURES="$OSMAND_FEATURES"
export APK_NUMBER_VERSION="$OSMAND_VERCODE"

sed -e '/qt.*Compile/d' -i build.gradle
sed -e '/signingConfig\s\+signingConfigs\./d' -i build.gradle
